### PR TITLE
Sort also enabled on dataview & datatable

### PR DESCRIPTION
**Pull request by AqibChattha**
Enabled sort for dataviews and datatables as well. Working with datatables I found out that the filtering was working on datatables, while the sorting was not working. So, In the source code I found this piece of code missing. I hope it helps 👍

### CODE REVIEW

**Comment by davidegironi** [comment]
Thank you for contributing.
Before merging it, have you tested this mods?

**Comment by davidegironi** [comment]
Thanks, within a few days I'll merge your mod.

**Comment by AqibChattha** [comment]
No problem at all sir 👍

**Comment by davidegironi** [comment]
Merged, I've just notice it was probably my oversight. I have done the same thing on filtering but not in sorting.

**Comment by AqibChattha** [comment]
Yes sir, that is what I thought as well 😅👍

**Pull request merged**
